name: CPAN-DistnameInfo
version: 0.03
abstract: Extract distribution name and version from a distribution filename
author: Graham Barr <gbarr@pobox.com>
license: perl
distribution_type: module
private:
  directory:
    - inc
generated_by: Module::Install version 0.24
