---
abstract: 'Extract distribution name and version from a distribution filename'
author:
  - 'Graham Barr <gbarr@pobox.com>'
configure_requires:
  ExtUtils::MakeMaker: 6.30
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CPAN-DistnameInfo
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.004
version: 0.07
